//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweets
    {
        public Tweets()
        {
            this.Favorites = new HashSet<Favorites>();
        }
    
        public int tweetID { get; set; }
        public int userID { get; set; }
        public string tweetText { get; set; }
        public int favSayisi { get; set; }
        public System.DateTime created_at { get; set; }
    
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual Users Users { get; set; }
    }
}
