//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Followers = new HashSet<Followers>();
            this.Tweets = new HashSet<Tweets>();
        }
    
        public int userID { get; set; }
        public string nickName { get; set; }
        public string Name { get; set; }
        public string lastName { get; set; }
        public bool cinsiyet { get; set; }
        public System.DateTime birthDate { get; set; }
        public string email { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<Followers> Followers { get; set; }
        public virtual ICollection<Tweets> Tweets { get; set; }
    }
}
